before_script:
  - mvn -v

stages:
  - test
  - deploy
  - docker

test:
  stage: test
  script:
    - mvn clean test

compile:
  stage: test
  script:
    - mvn clean compile

release:
  stage: deploy
  script:
    - mvn clean package -DskipTests=true
  artifacts:
    paths:
    - server/target/server*.jar
    - intermediate-model/target/intermediate-model*.jar

release-docker:
  stage: docker
  script:
    - docker-compose build
    - docker tag java-xal:0.1 thisthatdc/java-xal:0.1
    - docker push thisthatdc/java-xal:0.1

pages:
  stage: deploy
  script:
  - mvn clean package -DskipTests=true
  - mkdir .public
  - cp -r target/site/apidocs/ .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master