before_script:
  - mvn -v
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  - echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  - apt-get update
  - apt-get install -y maven
  - apt-get install -y mongodb-org

image: java:8

stages:
  - compile
  - test
  - deploy

compile:
  stage: compile
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn test

release:
  stage: deploy
  script:
    - mvn clean package -DskipTests=true
  artifacts:
    paths:
    - server/target/server*.jar
    - intermediate-model/target/intermediate-model*.jar
    - code-instrumentation/target/code-instrumentation*.jar

pages:
  stage: deploy
  script:
  - mvn clean package -DskipTests=true
  - mkdir .public
  - cp -r target/site/apidocs/ .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master