before_script:
  - mvn -v

test:
  script:
    - mvn clean test

compile:
  script:
    - mvn clean compile

deploy:
  script:
    - mvn clean package -DskipTests=true
  artifacts:
    paths:
    - server/target/server*.jar
    - intermediate-model/target/intermediate-model*.jar

pages:
  script:
    - mvn clean package -DskipTests=true
  artifacts:
    paths:
      - target/site/apidocs